<a href="https://colab.research.google.com/github/faheema2006/MLOPS/blob/main/SkillSync(Naive_Bayes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
dataset = pd.read_csv('/content/clean_resume_dataset.csv')
print(dataset.head())

    ResumeID        Category              Name              Email  \
0  REAL_0001  Java Developer      Chad Griffin  contact@email.com
1  REAL_0002  Java Developer    Melinda Thomas  contact@email.com
2  REAL_0003  Java Developer  Shannon Mccarthy  contact@email.com
3  REAL_0004  Java Developer  Christine Kelley  contact@email.com
4  REAL_0005  Java Developer        Karen Holt  contact@email.com

                                               Phone     Location  \
0  94105 555 4321000          10                 ...  City, State
1  17994568777  2017 2018 20152016       3       ...  City, State
2  9  555 4321000      94105   8                 ...  City, State
3  9  555 4321000      94105   5                 ...  City, State
4  100   10   4321000                            ...  City, State

                                             Summary                   Skills  \
0  jessica claire montgomery street san francisco...  Python, SQL, Git, Linux
1  jared arthur maica java developer 17994568777 ...  Python, SQL, Git, Linux
2  jessica claire 9 resumesampleexamplecom 555 43...  Python, SQL, Git, Linux
3  jessica claire 9 resumesampleexamplecom 555 43...  Python, SQL, Git, Linux
4  jessica claire 100 montgomery st 10th floor xx...  Python, SQL, Git, Linux

                                          Experience                Education  \
0  jessica claire montgomery street san francisco...  Computer Science degree
1  jared arthur maica java developer 17994568777 ...  Computer Science degree
2  jessica claire 9 resumesampleexamplecom 555 43...  Computer Science degree
3  jessica claire 9 resumesampleexamplecom 555 43...  Computer Science degree
4  jessica claire 100 montgomery st 10th floor xx...  Computer Science degree

                                                Text       Source
0  jessica claire montgomery street san francisco...  ResumeAtlas
1  jared arthur maica java developer 17994568777 ...  ResumeAtlas
2  jessica claire 9 resumesampleexamplecom 555 43...  ResumeAtlas
3  jessica claire 9 resumesampleexamplecom 555 43...  ResumeAtlas
4  jessica claire 100 montgomery st 10th floor xx...  ResumeAtlas

In [2]:
dataset.groupby('Category').describe()

                          ResumeID                          Name         \
                             count unique         top freq count unique
Category
AI Engineer                     71     71  SYNTH_2899    1    71     71
Backend Developer               76     76  SYNTH_2823    1    76     76
Blockchain                      47     47   REAL_2041    1    47     47
Blockchain Developer            30     30  SYNTH_3371    1    30     30
Business Analyst               150    150   REAL_2088    1   150    150
Cloud Engineer                  92     92  SYNTH_2574    1    92     92
Cybersecurity Analyst           66     66  SYNTH_2970    1    66     65
Data Science                   200    200   REAL_0401    1   200    200
Database                       150    150   REAL_0961    1   150    150
Database Administrator          56     56  SYNTH_3097    1    56     56
DevOps                         180    180   REAL_0601    1   180    180
Digital Media                  100    100   REAL_2238    1   100    100
DotNet Developer               140    140   REAL_1561    1   140    140
ETL Developer                  120    120   REAL_1701    1   120    120
Engineering Manager             30     30  SYNTH_3401    1    30     30
Frontend Developer              76     76  SYNTH_2747    1    76     75
Full Stack Developer           102    102  SYNTH_2472    1   102    102
Java Developer                 200    200   REAL_0001    1   200    198
Machine Learning Engineer       81     81  SYNTH_2666    1    81     81
Mobile Developer                46     46  SYNTH_3250    1    46     46
Network Security Engineer      120    120   REAL_1821    1   120    120
Principal Engineer              25     25  SYNTH_3431    1    25     25
Product Manager                 25     25  SYNTH_3456    1    25     25
Python Developer               200    200   REAL_0201    1   200    200
QA Engineer                     61     61  SYNTH_3036    1    61     61
React Developer                150    150   REAL_1411    1   150    150
SAP Developer                  100    100   REAL_1941    1   100     99
SQL Developer                  180    180   REAL_0781    1   180    180
Site Reliability Engineer       46     46  SYNTH_3204    1    46     46
Software Developer             134    134  SYNTH_2338    1   134    134
System Administrator            40     40  SYNTH_3296    1    40     40
Technical Lead                  35     35  SYNTH_3336    1    35     35
Technical Writer                20     20  SYNTH_3481    1    20     20
Testing                        150    150   REAL_1111    1   150    150
UI/UX Designer                  51     51  SYNTH_3153    1    51     51
Web Designing                  150    150   REAL_1261    1   150    150

                                                    Email         ...  \
                                           top freq count unique  ...
Category                                                          ...
AI Engineer                    Virginia Howard    1    71     71  ...
Backend Developer                Joseph Garcia    1    76     76  ...
Blockchain                       Gregory Smith    1    47      1  ...
Blockchain Developer                Lisa Smith    1    30     30  ...
Business Analyst                   Carlos Cook    1   150      1  ...
Cloud Engineer                      Diane Lara    1    92     92  ...
Cybersecurity Analyst               Jason Shaw    2    66     65  ...
Data Science                      Sharon Bowen    1   200      1  ...
Database                            John Ortiz    1   150      1  ...
Database Administrator           Carrie Curtis    1    56     56  ...
DevOps                             Julie Gomez    1   180      1  ...
Digital Media                   Kathryn Howard    1   100      1  ...
DotNet Developer                Linda Thompson    1   140      1  ...
ETL Developer                  Nicole Chambers    1   120      1  ...
Engineering Manager               Bobby Vargas    1    30     30  ...
Frontend Developer                 Peter Jones    2    76     76  ...
Full Stack Developer            Donna Espinoza    1   102    102  ...
Java Developer                Michael Williams    3   200      1  ...
Machine Learning Engineer      Robert Gonzalez    1    81     81  ...
Mobile Developer                   Becky Kline    1    46     46  ...
Network Security Engineer        Jonathan Dean    1   120      1  ...
Principal Engineer            Christopher Cobb    1    25     25  ...
Product Manager                     Cory James    1    25     25  ...
Python Developer                Steven Sweeney    1   200      1  ...
QA Engineer                   Margaret Freeman    1    61     61  ...
React Developer                    Judy Bailey    1   150      1  ...
SAP Developer                     Anthony Tran    2   100      1  ...
SQL Developer                     Philip Combs    1   180      1  ...
Site Reliability Engineer       Rebecca Rangel    1    46     46  ...
Software Developer            Danielle Johnson    1   134    134  ...
System Administrator                 Mark King    1    40     40  ...
Technical Lead                   Karen Ferrell    1    35     35  ...
Technical Writer               Lawrence Nelson    1    20     20  ...
Testing                    Dr. Brady Clark Jr.    1   150      1  ...
UI/UX Designer              Jacqueline Johnson    1    51     51  ...
Web Designing                  Virginia Nguyen    1   150      1  ...

                                                                   Education  \
                                                                         top
Category
AI Engineer                Master of Engineering in Software Engineering ...
Backend Developer          Bachelor of Science in Computer Science from U...
Blockchain                                           Computer Science degree
Blockchain Developer       Master of Engineering in Software Engineering ...
Business Analyst                                     Computer Science degree
Cloud Engineer             Bachelor of Science in Information Systems fro...
Cybersecurity Analyst      Bachelor of Technology in Information Technolo...
Data Science                                         Computer Science degree
Database                                             Computer Science degree
Database Administrator     Master of Science in Data Science from UC Berk...
DevOps                                               Computer Science degree
Digital Media                                        Computer Science degree
DotNet Developer                                     Computer Science degree
ETL Developer                                        Computer Science degree
Engineering Manager        Bachelor of Engineering in Software Engineerin...
Frontend Developer         Bachelor of Science in Information Systems fro...
Full Stack Developer       Bachelor of Engineering in Software Engineerin...
Java Developer                                       Computer Science degree
Machine Learning Engineer  Bachelor of Technology in Information Technolo...
Mobile Developer           Master of Science in Computer Science from Sta...
Network Security Engineer                            Computer Science degree
Principal Engineer         Master of Engineering in Software Engineering ...
Product Manager            Master of Science in Data Science from Carnegi...
Python Developer                                     Computer Science degree
QA Engineer                Bachelor of Engineering in Computer Engineerin...
React Developer                                      Computer Science degree
SAP Developer                                        Computer Science degree
SQL Developer                                        Computer Science degree
Site Reliability Engineer  Bachelor of Science in Information Systems fro...
Software Developer         Bachelor of Engineering in Computer Engineerin...
System Administrator       Bachelor of Science in Computer Science from U...
Technical Lead             Bachelor of Technology in Information Technolo...
Technical Writer           Bachelor of Science in Computer Science from H...
Testing                                              Computer Science degree
UI/UX Designer             Bachelor of Engineering in Software Engineerin...
Web Designing                                        Computer Science degree

                                Text         \
                          freq count unique
Category
AI Engineer                  1    71     71
Backend Developer            1    76     76
Blockchain                  47    47     43
Blockchain Developer         1    30     30
Business Analyst           150   150    143
Cloud Engineer               1    92     92
Cybersecurity Analyst        1    66     66
Data Science               200   200    189
Database                   150   150    143
Database Administrator       1    56     56
DevOps                     180   180    164
Digital Media              100   100     98
DotNet Developer           140   140    130
ETL Developer              120   120    114
Engineering Manager          1    30     30
Frontend Developer           1    76     76
Full Stack Developer         1   102    102
Java Developer             200   200    185
Machine Learning Engineer    1    81     81
Mobile Developer             1    46     46
Network Security Engineer  120   120    117
Principal Engineer           1    25     25
Product Manager              1    25     25
Python Developer           200   200    186
QA Engineer                  1    61     61
React Developer            150   150    142
SAP Developer              100   100     95
SQL Developer              180   180    171
Site Reliability Engineer    1    46     46
Software Developer           1   134    134
System Administrator         1    40     40
Technical Lead               1    35     35
Technical Writer             1    20     20
Testing                    150   150    148
UI/UX Designer               1    51     51
Web Designing              150   150    146

                                                                              \
                                                                         top
Category
AI Engineer                virginia howard virginia howard gmail com 696 ...
Backend Developer          joseph garcia email joseph garcia gmail com ph...
Blockchain                 ron phoenix blockchain developer 15491295157 d...
Blockchain Developer        lisa smith lisa smith gmail com 520 819 7121x...
Business Analyst           business analyst resume 3665 margaret street h...
Cloud Engineer              diane lara diane lara yahoo com 709 588 3920 ...
Cybersecurity Analyst      donald stewart email donald stewart gmail com ...
Data Science               jessica claire montgomery street san francisco...
Database                   bob markkula database developer phone 21492703...
Database Administrator     carrie curtis carrie curtis hotmail com 001 66...
DevOps                     first last cloud devops engineer devops engine...
Digital Media              social media resume resume genius profile mark...
DotNet Developer           jane fisher net developer phone 7576461653 ema...
ETL Developer              jonathan keller etl developer 2567514786 jonat...
Engineering Manager         bobby vargas bobby vargas yahoo com 001 896 8...
Frontend Developer          shannon cole shannon cole hotmail com 419 296...
Full Stack Developer       donna espinoza email donna espinoza yahoo com ...
Java Developer             jessica claire montgomery street san francisco...
Machine Learning Engineer  robert gonzalez email robert gonzalez gmail co...
Mobile Developer           becky kline becky kline gmail com 284 746 1777...
Network Security Engineer  experience zechariah hand 733 hickle ramp san ...
Principal Engineer          christopher cobb christopher cobb hotmail com...
Product Manager            cory james cory james gmail com 502 886 7202x0...
Python Developer           daryl jacobi 119 skylar landing phoenix az 1 5...
QA Engineer                margaret freeman email margaret freeman hotmai...
React Developer            glenn young reactjs developer experienced java...
SAP Developer              jessica claire montgomery street san francisco...
SQL Developer              robert smith plsql developer contact details 1...
Site Reliability Engineer  rebecca rangel email rebecca rangel hotmail co...
Software Developer         danielle johnson email danielle johnson yahoo ...
System Administrator       mark king mark king yahoo com 4065445475 north...
Technical Lead             karen ferrell karen ferrell hotmail com 1 875 ...
Technical Writer            lawrence nelson lawrence nelson gmail com 704...
Testing                    sun bogan 977 joshua key chicago il phone 1 55...
UI/UX Designer             jacqueline johnson jacqueline johnson gmail co...
Web Designing              allen chaudhart web designer phone 7814708889 ...

                               Source
                          freq  count unique          top freq
Category
AI Engineer                  1     71      1    Synthetic   71
Backend Developer            1     76      1    Synthetic   76
Blockchain                   4     47      1  ResumeAtlas   47
Blockchain Developer         1     30      1    Synthetic   30
Business Analyst             3    150      1  ResumeAtlas  150
Cloud Engineer               1     92      1    Synthetic   92
Cybersecurity Analyst        1     66      1    Synthetic   66
Data Science                 2    200      1  ResumeAtlas  200
Database                     3    150      1  ResumeAtlas  150
Database Administrator       1     56      1    Synthetic   56
DevOps                       3    180      1  ResumeAtlas  180
Digital Media                2    100      1  ResumeAtlas  100
DotNet Developer             3    140      1  ResumeAtlas  140
ETL Developer                3    120      1  ResumeAtlas  120
Engineering Manager          1     30      1    Synthetic   30
Frontend Developer           1     76      1    Synthetic   76
Full Stack Developer         1    102      1    Synthetic  102
Java Developer               2    200      1  ResumeAtlas  200
Machine Learning Engineer    1     81      1    Synthetic   81
Mobile Developer             1     46      1    Synthetic   46
Network Security Engineer    2    120      1  ResumeAtlas  120
Principal Engineer           1     25      1    Synthetic   25
Product Manager              1     25      1    Synthetic   25
Python Developer             3    200      1  ResumeAtlas  200
QA Engineer                  1     61      1    Synthetic   61
React Developer              3    150      1  ResumeAtlas  150
SAP Developer                2    100      1  ResumeAtlas  100
SQL Developer                2    180      1  ResumeAtlas  180
Site Reliability Engineer    1     46      1    Synthetic   46
Software Developer           1    134      1    Synthetic  134
System Administrator         1     40      1    Synthetic   40
Technical Lead               1     35      1    Synthetic   35
Technical Writer             1     20      1    Synthetic   20
Testing                      2    150      1  ResumeAtlas  150
UI/UX Designer               1     51      1    Synthetic   51
Web Designing                2    150      1  ResumeAtlas  150

[36 rows x 44 columns]

In [3]:
dataset['selected'] = dataset['Category'].apply(lambda x: 1 if x == 'Data Science' else 0)

In [4]:
dataset.head()

,ResumeID,Category,Name,Email,Phone,Location,Summary,Skills,Experience,Education,Text,Source,selected
0,REAL_0001,Java Developer,Chad Griffin,contact@email.com,94105 555 4321000 10 ...,"City, State",jessica claire montgomery street san francisco...,"Python, SQL, Git, Linux",jessica claire montgomery street san francisco...,Computer Science degree,jessica claire montgomery street san francisco...,ResumeAtlas,0
1,REAL_0002,Java Developer,Melinda Thomas,contact@email.com,17994568777 2017 2018 20152016 3 ...,"City, State",jared arthur maica java developer 17994568777 ...,"Python, SQL, Git, Linux",jared arthur maica java developer 17994568777 ...,Computer Science degree,jared arthur maica java developer 17994568777 ...,ResumeAtlas,0
2,REAL_0003,Java Developer,Shannon Mccarthy,contact@email.com,9 555 4321000 94105 8 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas,0
3,REAL_0004,Java Developer,Christine Kelley,contact@email.com,9 555 4321000 94105 5 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas,0
4,REAL_0005,Java Developer,Karen Holt,contact@email.com,100 10 4321000 ...,"City, State",jessica claire 100 montgomery st 10th floor xx...,"Python, SQL, Git, Linux",jessica claire 100 montgomery st 10th floor xx...,Computer Science degree,jessica claire 100 montgomery st 10th floor xx...,ResumeAtlas,0

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(dataset.Text,dataset.selected,test_size=0.2)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
v = CountVectorizer()

In [10]:
X_train_count = v.fit_transform(X_train.values)

In [11]:
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
from sklearn.naive_bayes import MultinomialNB

In [14]:
model = MultinomialNB()

In [15]:
model.fit(X_train_count,y_train)

MultinomialNB()

In [16]:
resumes = ['''Python SQL Machine Learning Deep Learning NLP Data Analysis''','''HTML CSS JavaScript React Web Design Bootstrap''']

In [17]:
resumes_count = v.transform(resumes)

In [18]:
model.predict(resumes_count)

array([1, 0])

In [19]:
X_test_count = v.transform(X_test)

In [20]:
model.score(X_test_count,y_test)

0.9614285714285714

In [21]:
from sklearn.pipeline import Pipeline

In [22]:
clf = Pipeline([('vectorizer', CountVectorizer()),('nb', MultinomialNB())])

In [23]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [24]:
clf.score(X_test,y_test)

0.9614285714285714

In [25]:
clf.predict(resumes)

array([1, 0])